#!/usr/bin/env bash
# This script audits subdomains and displays their DNS A records using dig and awk

domain=$1
subdomain=$2

get_record_info() {
  full_domain="$1"
  output=$(dig "$full_domain" +short)
  if [ -n "$output" ]; then
    echo "The subdomain ${1%%.*} is a A record and points to $output"
  else
    echo "The subdomain ${1%%.*} does not exist or has no A record"
  fi
}

if [ -n "$subdomain" ]; then
  get_record_info "$subdomain.$domain"
else
  for sub in www lb-01 web-01 web-02; do
    get_record_info "$sub.$domain"
  done
fi
