#!/usr/bin/env bash
# Configures custom 404 page for Nginx

apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use it
sed -i 's|error_page 404 /404.html;|error_page 404 /custom_404.html;|' /etc/nginx/sites-available/default
sed -i 's|location = /404.html {|location = /custom_404.html {|' /etc/nginx/sites-available/default

# Restart nginx
service nginx start || service nginx restart
